name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps: 
            - name: Checkout My repo
              uses: actions/checkout@main

            - name: List and read files
              run: | 
                echo "My First Github Action Job"
                ls -ltra
                cat README.md
            
            - name: Generate ASCII ArtWork
              run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt
            
            # - name: List files
            #   run: ls             
            # - name: Read file
            #   run: cat README.md
              






