name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps: 
            - name: Welcome message 
              run:  echo "My First Github Action Job"
            - name: Checkout My repo
              uses: actions/checkout@main
            - name: List files
              run: ls             
            - name: Read file
              run: cat README.md
              






